# Generated by Django 2.0 on 2018-06-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0002_auto_20180612_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
